sonar.projectKey=pensildevs-academy-web
sonar.projectName=Pensildevs Academy Web
sonar.projectVersion=0.0.0

sonar.sources=src

sonar.sourceEncoding=UTF-8

sonar.tests=src
sonar.test.inclusions=src/**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/pensildevs-academy-web/lcov.info

sonar.host.url=http://localhost:10000
